all: libguide libguidexv

libguide:
	cd share/src/libguide; make 

libguidexv:
	cd share/src/libguidexv; make 

demo:
	cd demo/xview/tree; make
install:
	cd share/src/libguide; make install
	cd share/src/libguidexv; make install

clean:
	cd share/src/libguide; make clean
	cd share/src/libguidexv; make clean
