#
#    SCCS ID: %Z%%M% %I% %E% SMI
#
#    Copyright (c) 1990-1992 Sun Microsystems, Inc.  All rights reserved.
#    See LEGAL_NOTICE file for terms of the license.
#
ss_examples:
	cd CSArrayTile; make
	cd CSDrawImage; make
	cd CSDrawText; make

ss_examples_svr4:
	cd CSArrayTile; make -f Makefile.svr4
	cd CSDrawImage; make -f Makefile.svr4
	cd CSDrawText; make -f Makefile.svr4

ss_examples_NO_XVPS:
	cd CSArrayTile; make -f Makefile.NO_XVPS
	cd CSDrawImage; make -f Makefile.NO_XVPS
	cd CSDrawText; make -f Makefile.NO_XVPS

ss_examples_svr4_NO_XVPS:
	cd CSArrayTile; make -f Makefile.svr4.NO_XVPS
	cd CSDrawImage; make -f Makefile.svr4.NO_XVPS
	cd CSDrawText; make -f Makefile.svr4.NO_XVPS

ss_examples_g++_NO_XVPS:
	cd CSArrayTile; make -f Makefile.g++.NO_XVPS
	cd CSDrawImage; make -f Makefile.g++.NO_XVPS
	cd CSDrawText; make -f Makefile.g++.NO_XVPS

delete:
	cd CSArrayTile; make delete
	cd CSDrawImage; make delete
	cd CSDrawText; make delete
