#
#    SCCS ID: %Z%%M% %I% %E% SMI
#
#    Copyright (c) 1990-1992 Sun Microsystems, Inc.  All rights reserved.
#    See LEGAL_NOTICE file for terms of the license.
#
examples:
	cd ColorMaps/Display; make
	cd ColorMaps/Worms; make
	cd DragAndDrop/Canvas; make
	cd DragAndDrop/Panel; make
	cd DragAndDrop/PrintTool; make
	cd HotRegions/Canvas/PostScript; make
	cd HotRegions/Canvas/Xlib; make
	cd HotRegions/Panel; make
	cd Images/Choice; make
	cd Images/List; make
	cd Menus; make
	cd NewUITClasses/PropertiesWindow; make
	cd NewUITClasses/Choosers; make choosers
	cd NotifyTargets; make
	cd PostScript/Circles; make
	cd PostScript/ImageButton; make
	cd Windows; make
	cd SlingShot; make ss_examples

examples_svr4:
	cd ColorMaps/Display; make -f Makefile.svr4
	cd ColorMaps/Worms; make -f Makefile.svr4
	cd HotRegions/Canvas/Xlib; make -f Makefile.svr4
	cd Images/Choice; make -f Makefile.svr4
	cd Images/List; make -f Makefile.svr4
	cd Menus; make -f Makefile.svr4
	cd NewUITClasses/PropertiesWindow; make -f Makefile.svr4
	cd NewUITClasses/Choosers; make choosers_svr4
	cd NotifyTargets; make -f Makefile.svr4
	cd Windows; make -f Makefile.svr4
	cd SlingShot; make ss_examples_svr4

examples_NO_XVPS:
	cd ColorMaps/Display; make -f Makefile.NO_XVPS
	cd ColorMaps/Worms; make -f Makefile.NO_XVPS
	cd HotRegions/Canvas/Xlib; make -f Makefile.NO_XVPS
	cd Images/Choice; make -f Makefile.NO_XVPS
	cd Images/List; make -f Makefile.NO_XVPS
	cd Menus; make -f Makefile.NO_XVPS
	cd NewUITClasses/PropertiesWindow; make -f Makefile.NO_XVPS
	cd NotifyTargets; make -f Makefile.NO_XVPS
	cd Windows; make -f Makefile.NO_XVPS
	cd SlingShot; make ss_examples_NO_XVPS

examples_svr4_NO_XVPS:
	cd ColorMaps/Display; make -f Makefile.svr4.NO_XVPS
	cd ColorMaps/Worms; make -f Makefile.svr4.NO_XVPS
	cd HotRegions/Canvas/Xlib; make -f Makefile.svr4.NO_XVPS
	cd Images/Choice; make -f Makefile.svr4.NO_XVPS
	cd Images/List; make -f Makefile.svr4.NO_XVPS
	cd Menus; make -f Makefile.svr4.NO_XVPS
	cd NewUITClasses/PropertiesWindow; make -f Makefile.svr4.NO_XVPS
	cd NotifyTargets; make -f Makefile.svr4.NO_XVPS
	cd Windows; make -f Makefile.svr4.NO_XVPS
	cd SlingShot; make ss_examples_svr4_NO_XVPS

examples_g++_NO_XVPS:
	cd ColorMaps/Display; make -f Makefile.g++.NO_XVPS
	cd ColorMaps/Worms; make -f Makefile.g++.NO_XVPS
	cd HotRegions/Canvas/Xlib; make -f Makefile.g++.NO_XVPS
	cd Images/Choice; make -f Makefile.g++.NO_XVPS
	cd Images/List; make -f Makefile.g++.NO_XVPS
	cd Menus; make -f Makefile.g++.NO_XVPS
	cd NewUITClasses/PropertiesWindow; make -f Makefile.g++.NO_XVPS
	cd NotifyTargets; make -f Makefile.g++.NO_XVPS
	cd OverviewExample; make -f Makefile.g++.NO_XVPS
	cd Windows; make -f Makefile.g++.NO_XVPS
	cd SlingShot; make ss_examples_g++_NO_XVPS

delete:
	cd ColorMaps/Display; make -i delete
	cd ColorMaps/Worms; make -i delete
	cd DragAndDrop/Canvas; make -i delete
	cd DragAndDrop/Panel; make -i delete
	cd DragAndDrop/PrintTool; make -i delete
	cd HotRegions/Canvas/PostScript; make -i delete
	cd HotRegions/Canvas/Xlib; make -i delete
	cd HotRegions/Panel; make -i delete
	cd Images/Choice; make -i delete
	cd Images/List; make -i delete
	cd Menus; make -i delete
	cd NewUITClasses/PropertiesWindow; make -i delete
	cd NewUITClasses/Choosers; make -i delete
	cd NotifyTargets; make -i delete
	cd PostScript/Circles; make -i delete
	cd PostScript/ImageButton; make -i delete
	cd Windows; make -i delete
	cd SlingShot; make delete
